<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.crane0927</groupId>
        <artifactId>saas-forge</artifactId>
        <version>${revision}</version>
        <relativePath>../../../pom.xml</relativePath>
    </parent>

    <artifactId>saas-forge-sdk-core</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpmime</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-openapi-rest-client</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${maven.multiModuleProjectDirectory}/contracts/openapi/v1.yaml</inputSpec>
                            <generatorName>java</generatorName>
                            <library>native</library>
                            <output>${project.build.directory}/generated-sources/openapi</output>
                            <apiPackage>io.saasforge.sdk.core.rest.api</apiPackage>
                            <modelPackage>io.saasforge.sdk.core.rest.model</modelPackage>
                            <invokerPackage>io.saasforge.sdk.core.rest</invokerPackage>
                            <configOptions>
                                <dateLibrary>java8</dateLibrary>
                                <serializationLibrary>jackson</serializationLibrary>
                                <openApiNullable>false</openApiNullable>
                                <useJakartaEe>true</useJakartaEe>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
