import { createApp } from 'vue';
import { createPinia } from 'pinia';
import { ElLoading } from 'element-plus';
import App from './App.vue';
import { router } from './router';
import { setupI18n } from './locales';
import './styles/index.css';
const app = createApp(App);
setupI18n(app);
app.use(createPinia()).use(router).directive('loading', ElLoading.directive).mount('#app');
